server {
    listen       8080;
    server_name  localhost;

    root /usr/share/nginx/html;
    # Prefer index.html as the index file
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
